### ISSUE TITLE
Training and Testing Code

### ISSUE THREAD

**Issue by jiandandan001** [visipedia/caltech-fish-counting#4]
Thank you for sharing the dataset.

Could you please share the model training and testing code?  Thanks

**Comment by justinkay** [comment]
Hi, thanks for your interest! 

We used official open source code for our baselines:
[YOLOv5](https://github.com/ultralytics/yolov5) for detector training,
[SORT](https://github.com/abewley/sort) for object tracking.

Training settings are included in our supplemental material.

Code for generating the frames for our Baseline++ method is convert.py.

**Comment by justinkay** [comment]
(And evaluation code is in evaluate.py)
