### ISSUE TITLE
Mismatched number of frames in annotations vs raw for TinyDataset.

### ISSUE THREAD

**Issue by aaprasad** [visipedia/caltech-fish-counting#6]
Hi, I'm playing around with the tiny version of this dataset and when I inspected `tiny_dataset/annotations-tiny/elwha/Elwha_2018_OM_ARIS_2018_07_09_2018-07-09_190000_490_941/gt_tiny.txt`, it seems to contain 47 frames ranging from 208-254. However, when I look at the raw data at `tiny_dataset/raw/elwha/Elwha_2018_OM_ARIS_2018_07_09_2018-07-09_190000_490_941`, there seems to be 50 frames ranging from 197 to 246. What explains the discrepancy I'm seeing?

**Comment by suzanne-stathatos** [comment]
Hey! The frames that are annotated have fish in them. The frames that are not annotated do not have any fish. So, the raw frames include some frames with no fish.
