### ISSUE TITLE
Polar images

### ISSUE THREAD

**Issue by Pikstar** [visipedia/caltech-fish-counting#9]
Hello,
so far great work. You clearly improve the state of databases in terms of underwater sonar imagery.
Probably not a github issue, but:

For some applications, the polar (an thus rectangular shaped) images are beneficial. Is there any option to get the polar images (at best with annotations)?

Thank you and kind regards

**Comment by justinkay** [comment]
Hi @Pikstar thanks for the suggestion! We have actually been thinking about releasing some of the raw sonar data and/or polar images so it's great to hear this would be useful for you. We'd be interested to hear more about your use case, if you'd like to chat please shoot me an email! kayj@mit.edu
